language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
#sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - LINUX_SRC=linux
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Adafruit_Bluefruit_LE
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Arduino_101_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=genuino101"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/DFRobot_Bluno_BLE_Link PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/LightBlue_Bean PLATFORMIO_CI_EXTRA_ARGS="--board=lightblue-bean"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Microduino_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RFDuino_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=rfduino"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RedBearLab_BLE_Mini PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RedBearLab_BlendMicro PLATFORMIO_CI_EXTRA_ARGS="--board=blendmicro8"
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RedBear_Duo_BLE
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Serial_HC05_HC06
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Serial_HM10_HC08 PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Simblee_BLE
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/nRF8001
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Arduino_Ethernet
    # - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Arduino_Ethernet2
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Arduino_Ethernet_Manual
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/ENC28J60 PLATFORMIO_CI_EXTRA_ARGS="--board=nanoatmega328"
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Energia_Ethernet PLATFORMIO_CI_EXTRA_ARGS="--board=lptm4c1294ncpdt"
    # - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Intel_Galileo
    # - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Seeed_EthernetV2_0
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/ATtiny85 PLATFORMIO_CI_EXTRA_ARGS="--board=attiny85"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Arduino_Serial_USB
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Arduino_SoftwareSerial
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Arduino_Zero_M0_Serial PLATFORMIO_CI_EXTRA_ARGS="--board=zero"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Blue_Pill_STM32F103C PLATFORMIO_CI_EXTRA_ARGS="--board=bluepill_f103c8 --project-option='framework=arduino'"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Digistump_Digispark PLATFORMIO_CI_EXTRA_ARGS="--board=digispark-pro"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Energia_Serial_USB PLATFORMIO_CI_EXTRA_ARGS="--board=lplm4f120h5qr"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Teensy3 PLATFORMIO_CI_EXTRA_ARGS="--board=teensy31"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/User_Defined_Connection
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/chipKIT_Uno32 PLATFORMIO_CI_EXTRA_ARGS="--board=uno_pic32"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_MKR1000
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_WiFi_Shield
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_WiFi_Shield_101
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_Yun PLATFORMIO_CI_EXTRA_ARGS="--board=yun"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/CC3000
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Digistump_Oak
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Shield PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Standalone PLATFORMIO_CI_EXTRA_ARGS="--board=esp01"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Standalone_SSL PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Standalone_SmartConfig PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Energia_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=lpmsp430f5529"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Intel_Edison_WiFi
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/LinkItONE
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/RN_XV_WiFly PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/RedBear_Duo_WiFi
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Sparkfun_Blynk_Board PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/TheAirBoard_WiFly PLATFORMIO_CI_EXTRA_ARGS="--board=fio"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/TinyDuino_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=tinyduino"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/WildFire_V3 PLATFORMIO_CI_EXTRA_ARGS="--board=wildfirev3"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/WildFire_V4
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/ESP8266_ReadPin PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/ESP8266_WritePin PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/Ethernet_ReadPin
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/Ethernet_WritePin
    - PLATFORMIO_CI_SRC=examples/Export_Demo/Template_MKR1000 PLATFORMIO_CI_EXTRA_ARGS="--board=mkr1000USB"
    - PLATFORMIO_CI_SRC=examples/Export_Demo/myPlant_ESP8266 PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2 --project-option='lib_ignore=WiFi101'"
    - PLATFORMIO_CI_SRC=examples/GettingStarted/BlynkBlink
    - PLATFORMIO_CI_SRC=examples/GettingStarted/GetData
    - PLATFORMIO_CI_SRC=examples/GettingStarted/PushData
    - PLATFORMIO_CI_SRC=examples/GettingStarted/PushDataOnRequest
    - PLATFORMIO_CI_SRC=examples/GettingStarted/Servo
    - PLATFORMIO_CI_SRC=examples/More/DHT11
    - PLATFORMIO_CI_SRC=examples/More/FormatString
    - PLATFORMIO_CI_SRC=examples/More/NeoPixel
    - PLATFORMIO_CI_SRC=examples/More/PrintAllVirtual
    - PLATFORMIO_CI_SRC=examples/More/ServerAsDataStorage/ServerAsDataStorage_MultiValue
    - PLATFORMIO_CI_SRC=examples/More/ServerAsDataStorage/ServerAsDataStorage_SingleValue
    - PLATFORMIO_CI_SRC=examples/More/SetProperty/SetProperty_MultiValue
    - PLATFORMIO_CI_SRC=examples/More/SetProperty/SetProperty_SingleValue
    - PLATFORMIO_CI_SRC=examples/More/Stroboscope
    - PLATFORMIO_CI_SRC=examples/More/Sync/ButtonInterrupt
    - PLATFORMIO_CI_SRC=examples/More/Sync/ButtonPoll
    - PLATFORMIO_CI_SRC=examples/More/Sync/HardwareSyncStateFromApp
    - PLATFORMIO_CI_SRC=examples/More/Sync/SyncPhysicalButton
    - PLATFORMIO_CI_SRC=examples/Widgets/Bridge
    - PLATFORMIO_CI_SRC=examples/Widgets/Email
    - PLATFORMIO_CI_SRC=examples/Widgets/Eventor
    - PLATFORMIO_CI_SRC=examples/Widgets/GPS_Stream
    - PLATFORMIO_CI_SRC=examples/Widgets/JoystickTwoAxis
    - PLATFORMIO_CI_SRC=examples/Widgets/LCD/LCD_AdvancedMode
    - PLATFORMIO_CI_SRC=examples/Widgets/LED/LED_StatusOfButton
    - PLATFORMIO_CI_SRC=examples/Widgets/Menu
    - PLATFORMIO_CI_SRC=examples/Widgets/Player
    - PLATFORMIO_CI_SRC=examples/Widgets/PushNotification/PushNotification_Button
    - PLATFORMIO_CI_SRC=examples/Widgets/RTC
    - PLATFORMIO_CI_SRC=examples/Widgets/SDcard
    - PLATFORMIO_CI_SRC=examples/Widgets/Table/Table_Advanced
    - PLATFORMIO_CI_SRC=examples/Widgets/Table/Table_Simple
    - PLATFORMIO_CI_SRC=examples/Widgets/Terminal
    - PLATFORMIO_CI_SRC=examples/Widgets/TimeInput/AdvancedTimeInput
    - PLATFORMIO_CI_SRC=examples/Widgets/TimeInput/SimpleTimeInput
    - PLATFORMIO_CI_SRC=examples/Widgets/Timer
    - PLATFORMIO_CI_SRC=examples/Widgets/Twitter

install:
    # tmp solution, use 32-bits toolchain for chipKIT_Uno32
    - sudo apt-get install -qq lib32z1 lib32ncurses5 lib32bz2-1.0

    - pip install -U https://github.com/platformio/platformio/archive/develop.zip
    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/44/Time
    # http://platformio.org/lib/show/419/SimpleTimer
    #
    # http://platformio.org/lib/show/17/Adafruit-CC3000
    # http://platformio.org/lib/show/28/SPI4Teensy3
    # http://platformio.org/lib/show/91/UIPEthernet
    # http://platformio.org/lib/show/418/WildFireCore
    # http://platformio.org/lib/show/420/WildFire-CC3000
    # http://platformio.org/lib/show/65/WiFlyHQ
    # http://platformio.org/lib/show/19/Adafruit-DHT
    # http://platformio.org/lib/show/299/WiFi101
    # http://platformio.org/lib/show/259/BLEPeripheral
    # http://platformio.org/lib/show/177/Adafruit_BluefruitLE_nRF51

    - platformio lib -g install 17 28 91 418 419 420 65 44 19 299 259 177 https://github.com/vshymanskyy/BlynkESP8266.git https://github.com/cmaglie/FlashStorage.git https://github.com/michael71/Timer5.git

script: make travis-build
