language: python
python:
    - "3.8"

# Cache PlatformIO packages using Travis CI container-based infrastructure
#sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - LINUX_SRC=linux
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Adafruit_Bluefruit_LE
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Adafruit_Feather_32u4_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=feather32u4 --project-option='lib_deps=SoftwareSerial'"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Arduino_101_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=genuino101"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/BBC_MicroBit PLATFORMIO_CI_EXTRA_ARGS="--board=uno --project-option='lib_deps=SPI'"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/DFRobot_Bluno_BLE_Link PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Energia_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=..."
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/LightBlue_Bean PLATFORMIO_CI_EXTRA_ARGS="--board=lightblue-bean"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Microduino_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RFDuino_BLE PLATFORMIO_CI_EXTRA_ARGS="--board=rfduino"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RedBearLab_BLE_Mini PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RedBearLab_BLE_Nano PLATFORMIO_CI_EXTRA_ARGS="--board=redBearLabBLENano --project-option='framework=arduino'"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RedBearLab_BlendMicro PLATFORMIO_CI_EXTRA_ARGS="--board=blendmicro8"
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/RedBear_Duo_BLE
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Serial_HC05_HC06
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Serial_HM10_HC08 PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/Simblee_BLE
    # - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/TheAirBoard_BLE_Link PLATFORMIO_CI_EXTRA_ARGS="--board=fio"
    - PLATFORMIO_CI_SRC=examples/Boards_Bluetooth/nRF8001
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Arduino_Ethernet
    # - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Arduino_Ethernet2
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Arduino_Ethernet_Manual
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/ENC28J60 PLATFORMIO_CI_EXTRA_ARGS="--board=nanoatmega328"
    - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Energia_Ethernet PLATFORMIO_CI_EXTRA_ARGS="--board=lptm4c1294ncpdt"
    # - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Intel_Galileo
    # - PLATFORMIO_CI_SRC=examples/Boards_Ethernet/Seeed_EthernetV2_0
    - PLATFORMIO_CI_SRC=examples/Boards_GSM/TinyGSM_SIM800_SIM900 PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/ATtiny85 PLATFORMIO_CI_EXTRA_ARGS="--board=attiny85"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Arduino_Serial_USB
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Arduino_SoftwareSerial
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Arduino_Zero_M0_Serial PLATFORMIO_CI_EXTRA_ARGS="--board=zero"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Blue_Pill_STM32F103C PLATFORMIO_CI_EXTRA_ARGS="--board=bluepill_f103c8 --project-option='framework=arduino'"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Digistump_Digispark PLATFORMIO_CI_EXTRA_ARGS="--board=digispark-pro"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Energia_Serial_USB PLATFORMIO_CI_EXTRA_ARGS="--board=lplm4f120h5qr"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/Teensy3 PLATFORMIO_CI_EXTRA_ARGS="--board=teensy31"
    - PLATFORMIO_CI_SRC=examples/Boards_USB_Serial/chipKIT_Uno32 PLATFORMIO_CI_EXTRA_ARGS="--board=uno_pic32"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Adafruit_Feather_M0_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=adafruit_feather_m0 --project-option='lib_deps=SPI, WiFi101'"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_MKR1000 PLATFORMIO_CI_EXTRA_ARGS="--board=mkr1000USB --project-option='lib_deps=WiFi101'"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_WiFi_Shield
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_WiFi_Shield_101 PLATFORMIO_CI_EXTRA_ARGS="--board=uno --project-option='lib_deps=WiFi101'"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_Yun PLATFORMIO_CI_EXTRA_ARGS="--board=yun"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Arduino_org_UNO_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=uno --project-option='lib_deps=WiFi Link' --project-option='build_flags=-DESP_CH_SPI'"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/CC3000 PLATFORMIO_CI_EXTRA_ARGS="--board=uno --project-option='lib_deps=Adafruit CC3000 Library'"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Digistump_Oak
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP32_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=esp32dev --project-option='framework=arduino'"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Shield PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Standalone PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Standalone_Manual_IP PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Standalone_SSL PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/ESP8266_Standalone_SmartConfig PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Energia_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=lpmsp430f5529"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Fishino
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Intel_Edison_WiFi
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/LinkItONE
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/NodeMCU PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/RN_XV_WiFly PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/RedBear_Duo_WiFi
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/Sparkfun_Blynk_Board PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/TheAirBoard_WiFly PLATFORMIO_CI_EXTRA_ARGS="--board=fio"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/TinyDuino_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=tinyduino --project-option='lib_deps=Adafruit CC3000 Library'"
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/WildFire_V3 PLATFORMIO_CI_EXTRA_ARGS="--board=wildfirev3 --project-option='lib_deps=WildFire-CC3000'"
    # - PLATFORMIO_CI_SRC=examples/Boards_WiFi/WildFire_V4
    - PLATFORMIO_CI_SRC=examples/Boards_WiFi/WizFi310 PLATFORMIO_CI_EXTRA_ARGS="--board=uno --project-option='lib_deps=WizFi310'"
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/Arduino_Ethernet
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/Arduino_GSM
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/ESP8266 PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/Boards_With_HTTP_API/SIM800_SIM900 PLATFORMIO_CI_EXTRA_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/Blynk.Inject/Template_ESP8266 PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2 --project-option='build_flags=-DBOARD_LED_PIN_WS2812 -DUSE_TICKER'"
    - PLATFORMIO_CI_SRC=examples/Blynk.Inject/Template_ESP32 PLATFORMIO_CI_EXTRA_ARGS="--board=esp32dev --project-option='framework=arduino'"
    - PLATFORMIO_CI_SRC=examples/Blynk.Inject/Template_MKR1000 PLATFORMIO_CI_EXTRA_ARGS="--board=mkr1000USB --project-option='lib_deps=WiFi101' --project-option='build_flags=-DUSE_TIMER_FIVE'"
    - PLATFORMIO_CI_SRC=examples/Blynk.Inject/myPlant_ESP8266 PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2 --project-option='build_flags=-DBOARD_LED_PIN_WS2812 -DUSE_TICKER'"
    - PLATFORMIO_CI_SRC=examples/GettingStarted/BlynkBlink
    - PLATFORMIO_CI_SRC=examples/GettingStarted/GetData
    - PLATFORMIO_CI_SRC=examples/GettingStarted/PushData
    - PLATFORMIO_CI_SRC=examples/GettingStarted/PushDataOnRequest
    - PLATFORMIO_CI_SRC=examples/GettingStarted/Servo
    - PLATFORMIO_CI_SRC=examples/GettingStarted/VirtualPinRead
    - PLATFORMIO_CI_SRC=examples/GettingStarted/VirtualPinReply
    - PLATFORMIO_CI_SRC=examples/GettingStarted/VirtualPinWrite
    - PLATFORMIO_CI_SRC=examples/More/AppConnectedEvents
    - PLATFORMIO_CI_SRC=examples/More/ArduinoClient/Arduino_Ethernet
    - PLATFORMIO_CI_SRC=examples/More/ArduinoClient/ESP8266_WiFi PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/More/DHT11 PLATFORMIO_CI_EXTRA_ARGS="--board=uno --project-option='lib_deps=Adafruit Unified Sensor'"
    - PLATFORMIO_CI_SRC=examples/More/DirectConnect/ESP8266_AccessPoint PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/More/DirectConnect/ESP8266_Station PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/More/FormatString
    - PLATFORMIO_CI_SRC=examples/More/HandleDisconnect PLATFORMIO_CI_EXTRA_ARGS="--board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/More/NeoPixel
    - PLATFORMIO_CI_SRC=examples/More/PrintAllVirtual
    - PLATFORMIO_CI_SRC=examples/More/ServerAsDataStorage/ServerAsDataStorage_MultiValue
    - PLATFORMIO_CI_SRC=examples/More/ServerAsDataStorage/ServerAsDataStorage_SingleValue
    - PLATFORMIO_CI_SRC=examples/More/SetProperty/SetProperty_MultiValue
    - PLATFORMIO_CI_SRC=examples/More/SetProperty/SetProperty_SingleValue
    - PLATFORMIO_CI_SRC=examples/More/Stroboscope
    - PLATFORMIO_CI_SRC=examples/More/Sync/ButtonInterrupt
    - PLATFORMIO_CI_SRC=examples/More/Sync/ButtonPoll
    - PLATFORMIO_CI_SRC=examples/More/Sync/HardwareSyncStateFromApp
    - PLATFORMIO_CI_SRC=examples/More/Sync/SyncPhysicalButton
    - PLATFORMIO_CI_SRC=examples/Widgets/Bridge
    - PLATFORMIO_CI_SRC=examples/Widgets/Email
    - PLATFORMIO_CI_SRC=examples/Widgets/Eventor
    - PLATFORMIO_CI_SRC=examples/Widgets/GPS_Stream
    - PLATFORMIO_CI_SRC=examples/Widgets/JoystickTwoAxis
    - PLATFORMIO_CI_SRC=examples/Widgets/LCD/LCD_AdvancedMode
    - PLATFORMIO_CI_SRC=examples/Widgets/LCD/LCD_SimpleModePushing
    - PLATFORMIO_CI_SRC=examples/Widgets/LCD/LCD_SimpleModeReading
    - PLATFORMIO_CI_SRC=examples/Widgets/LED/LED_Blink
    - PLATFORMIO_CI_SRC=examples/Widgets/LED/LED_Color
    - PLATFORMIO_CI_SRC=examples/Widgets/LED/LED_Fade
    - PLATFORMIO_CI_SRC=examples/Widgets/LED/LED_StatusOfButton
    - PLATFORMIO_CI_SRC=examples/Widgets/Map
    - PLATFORMIO_CI_SRC=examples/Widgets/Menu
    - PLATFORMIO_CI_SRC=examples/Widgets/Player
    - PLATFORMIO_CI_SRC=examples/Widgets/PushNotification/PushNotification_Button
    - PLATFORMIO_CI_SRC=examples/Widgets/PushNotification/PushNotification_Interval
    - PLATFORMIO_CI_SRC=examples/Widgets/RTC
    - PLATFORMIO_CI_SRC=examples/Widgets/RTC_Advanced
    - PLATFORMIO_CI_SRC=examples/Widgets/Table/Table_Advanced
    - PLATFORMIO_CI_SRC=examples/Widgets/Table/Table_Simple
    - PLATFORMIO_CI_SRC=examples/Widgets/Terminal
    - PLATFORMIO_CI_SRC=examples/Widgets/TimeInput/AdvancedTimeInput
    - PLATFORMIO_CI_SRC=examples/Widgets/TimeInput/SimpleTimeInput
    - PLATFORMIO_CI_SRC=examples/Widgets/TimeInput/UpdateTimeInputState
    - PLATFORMIO_CI_SRC=examples/Widgets/Timer
    - PLATFORMIO_CI_SRC=examples/Widgets/Twitter
    - PLATFORMIO_CI_SRC=examples/Widgets/WebHook/WebHook_GET

install:
    # ChipKIT issue: install 32-bit support for GCC PIC32
    - sudo apt-get install libc6-i386

    - pip install -U platformio

    #
    # Libraries from PlatformIO Library Registry:
    #
    # https://platformio.org/lib/show/28/SPI4Teensy3
    # https://platformio.org/lib/show/31/Adafruit%20Unified%20Sensor
    # https://platformio.org/lib/show/91/UIPEthernet
    # https://platformio.org/lib/show/418/WildFireCore
    # https://platformio.org/lib/show/65/WiFlyHQ
    # https://platformio.org/lib/show/44/Time
    # https://platformio.org/lib/show/31/Adafruit%20Unified%20Sensor
    # https://platformio.org/lib/show/19/Adafruit-DHT
    # https://platformio.org/lib/show/259/BLEPeripheral
    # https://platformio.org/lib/show/177/Adafruit_BluefruitLE_nRF51
    # https://platformio.org/lib/show/1192/FlashStorage
    # https://platformio.org/lib/show/1285/Timer5
    # https://platformio.org/lib/show/1287/TinyGSM
    # https://platformio.org/lib/show/870/WiFi
    # https://platformio.org/lib/show/871/GSM
    # https://platformio.org/lib/show/872/Ethernet
    # https://platformio.org/lib/show/883/Servo
    # https://platformio.org/lib/show/945/Bridge

    - platformio lib -g install 28 31 91 418 65 44 31 19 259 177 1192 1285 1287 870 871 872 883 945
    - platformio lib -g install https://github.com/vshymanskyy/BlynkESP8266.git

script: make travis-build
